import type { Metadata } from 'next'
import { RenderMounted } from '@/components/render-mounted'
import { jose, unna } from '@/app/fonts'
import { Suspense } from 'react'
import Loading from '@/components/loading'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${unna.variable} ${jose.variable} antialiased relative pb-24 xl:pb-40 min-h-screen`}
			>
				<RenderMounted>
					<Suspense fallback={<Loading />}>{children}</Suspense>
				</RenderMounted>
			</body>
		</html>
	)
}
